name: Sync deploy repo

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone deploy repo
        env:
          DEPLOY_TOKEN: ${{secrets.DEPLOY_TOKEN}}
        uses: actions/checkout@v4
        with:
          repository: "Kornellen/quizgame_deploy"
          ref: "main"
          token: ${DEPLOY_TOKEN}
          path: "../deploy"

      - name: Copy source code
        run: |
          rsync --delete -av --exclude='.git' --exclude='node_modules' --exclude='.env' ./ ../deploy/

      - name: Commit & push to deploy repo
        working-directory: ../deploy
        run: |
          git add .
          git commit -m "Sync from quizgame repo" || echo "No changes to commit"
          git push origin main
