name: Sync deploy repo

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          ls -l

      - name: Clone deploy repo
        env:
          DEPLOY_TOKEN: ${{secrets.DEPLOY_TOKEN}}
        run: |
          mkdir ../deploy
          git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/Kornellen/quizgame_deploy.git ../deploy
          pwd
          cd ../deploy
          git checkout main || git checkout -b main

      - name: Copy source code
        run: |
          pwd
          rsync --delete -av --exclude='.git' --exclude='node_modules' --exclude='.env' ../quizgame/ ../deploy/
          cd ../deploy

      - name: Commit & push to deploy repo
        run: |
          git add .
          git commit -m "Sync from quizgame repo" || echo "No changes to commit"
          git push origin main
